### ISSUE TITLE
the theroy tex doesn't work well 

### ISSUE THREAD

**Issue by JinxinHu** [miRoox/Math-Pysics-Exercises#1]
乱码

**Comment by miRoox** [comment]
编码是 GB2312 。当时刚接触LaTeX，用的是[物理学报](http://wulixb.iphy.ac.cn/CN/column/column1299.shtml)的模版，它的模版本身就是GB2312编码，如果不同样采用GB2312，反而会报错。而且必须要按 LaTeX 生成dvi再 dvi2pdf 的顺序处理，不能用pdfLaTeX等其它方式处理。
